plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

remote_theme: zivong/jekyll-theme-hamilton

title: "Phat's Journal"
description: "Đây là website ghi lại tất cả những gì của Phát, mọi thứ sẽ update lên đây, nếu rảnh"
author: "Phat Nguyen"
email: ""
lang: vi
timezone: Asia/Ho_Chi_Minh

url: "https://phat8507.github.io"
baseurl: "/tpdailyblog"

skin: midnight
avatar: /assets/avatar.png

paginate: 10
permalink: /:year/:month/:day/:title/
